# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Ferret Voice Podcast
email: voiceferretcom@gmail.com
description: "All information about keeping pet ferrets. Ferrets are incredibly potential pet, If you're considering choosing a ferret, learn more about ferrets care needs, including what you'll need and how to keep your ferret healthy etc. more information check out https://ferretvoice.com"
subtitle: ""
lang: en-us
author: Harry Rowland
copyright: "&#xA9; 2021"
baseurl: "/podcast" # the subpath of your site, e.g. /blog
url: "https://noehale.github.io" # the base hostname & protocol for your site
twitter_username: voiceferret
github_username: voiceferret

permalink: /:year/:title.html

#Timezone
timezone: United States/New York

#Setup for Pages
include: ['_pages']

# Build settings
markdown: kramdown

#Exclude local build settings
exclude: ['readme.md', 'Gemfile.lock', 'Gemfile']

theme: jekyll-theme-minimal
